version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'test-topic:1:1'
  app1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3001
      - KAFKA_BROKER=kafka:9092
    container_name: nestjs_app_1
    depends_on:
      - kafka

  app2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - PORT=3002
      - KAFKA_BROKER=kafka:9092
    container_name: nestjs_app_2
    depends_on:
      - kafka

  app3:
    build: .
    ports:
      - "3003:3000"
    environment:
      - PORT=3003
      - KAFKA_BROKER=kafka:9092
    container_name: nestjs_app_3
    depends_on:
      - kafka